
cc_library(
	name = "core",
	hdrs = ["comparison.h",
	        "interfaces.h",
	 "settings.h","buttons.h","events.h","maintain_hvac.h","settings_storer.h","calculate_iaq_score.h","fan_controller.h","menus.h"],
	copts = ["-Ithermostat", "-I../testing"],
	visibility = ["//visibility:public"],
	)
